/*
  The laboratory cover photographs.

  Moved out of `src/lib/learnerLabs.ts` so the home page can read it without
  pulling that module in. `learnerLabs` imports Prisma's generated types and
  every authored guide through `getLabGuide`; importing it from a client
  component would put the whole guide corpus in the browser bundle to fetch
  eleven image paths. This file is paths and colours only.

  `learnerLabs` re-exports what it used to own, so nothing that imported from
  there had to change.
*/

/**
 * Labs whose card leads with a photograph rather than a screenshot of the app.
 *
 * Filenames carry a hash of their own contents, generated by
 * `scripts/hash-lab-covers.mjs`. Replacing a picture in place keeps its URL,
 * and optimised images go out with `Cache-Control: max-age=14400`, so every
 * browser that saw the old one keeps showing it for four hours — which is
 * exactly what happened when the RepurposeAI cover was swapped. Re-run that
 * script after changing anything in `public/labs/` and paste the paths here.
 *
 * The default card image is the demo poster — a screenshot of the lab's own
 * interface. That works for a tool whose screen is the point, but for these
 * the subject is what the learner is actually studying, and a browser window
 * full of panels says less about it than the instrument or the specimen does.
 * The screenshots are untouched: the demo video still opens on its own poster
 * inside the lab page.
 *
 * `credit` is the source line for a photograph that is not ours to use
 * unattributed. It is rendered on the image itself, because the card is the
 * only place these appear — the lab page leads with the demo poster — and an
 * attribution nobody can see is not an attribution.
 */
export type CoverPhoto = {
  src: string;
  credit?: string;
  /**
   * The photograph's own average colour across its bottom 18% — the band the
   * credit sits over.
   *
   * The strip is not painted in this colour; it is painted in a pale wash of
   * it (see the card). A black gradient fought every picture it was laid over,
   * and simply using the measured colour was no better: average a photograph
   * of pink, teal and red bacteria and you get mud — #624f55 — which is dark
   * enough to read as the same black bar. Carrying the hue and lightening it
   * gives a strip that belongs to the image without going dark on it.
   */
  tint: string;
  /**
   * The colour the photograph actually ends in — the average of its last 4% of
   * rows, not a broad band.
   *
   * This is what the card carries downward: the credit strip rises out of it
   * and the body fades from it, so the panel below the picture reads as the
   * same object rather than a dark box bolted underneath. Sampling a wide band
   * would average in content nobody sees at the seam.
   */
  edge: string;
  /** Whether that edge is light enough to need dark ink over it. */
  edgeIsLight?: boolean;
};

export const COVER_PHOTO: Record<string, CoverPhoto> = {
  "denovo-genai-lab": { src: "/labs/denovo-genai-lab.9d533526.jpg", tint: "#303438", edge: "#24282b" },
  "drugdiscovery-ai": { src: "/labs/drugdiscovery-ai.5f1f39da.jpg", tint: "#cbc0c6", edge: "#c8cbd9", edgeIsLight: true },
  "micro-ai": {
    src: "/labs/micro-ai.0ec11f8b.jpg",
    tint: "#624f55", edge: "#645157",
    credit: "Yong, E. Microbiome sequencing offers hope for diagnostics. Nature (2012)",
  },
  omicslab: { src: "/labs/omicslab.9a645e33.jpg", tint: "#888990", edge: "#8c8a88" },
  fraudshield: { src: "/labs/fraudshield.ee467982.jpg", tint: "#3a4045", edge: "#323b43" },
  logiclab: { src: "/labs/logiclab.32701fc0.jpg", tint: "#b9b9bc", edge: "#c2c4c8", edgeIsLight: true },
  "ai-6g": { src: "/labs/ai-6g.41186ec2.jpg", tint: "#b7b6b9", edge: "#c9cbcf", edgeIsLight: true },
  "cognicore-ai": { src: "/labs/cognicore-ai.986765af.jpg", tint: "#807462", edge: "#75685a" },
  "battery-ai": { src: "/labs/battery-ai.1f25baae.jpg", tint: "#1e242c", edge: "#12161a" },
  metamaterials: { src: "/labs/metamaterials.8c99e225.jpg", tint: "#424548", edge: "#434649" },
  "virtual-ai": { src: "/labs/virtual-ai.82c2a62d.jpg", tint: "#918a8a", edge: "#736e6f" },
};
